CREATE TABLE IF NOT EXISTS SETTLED_INVOICE_RECEIVED_VIA
(
    "SETTLED_INVOICE_JPA_DTO_ADD_INDEX" BIGINT NOT NULL,
    "AMOUNT"                            BIGINT NOT NULL,
    "CHANNEL_ID"                        BIGINT NOT NULL
);

ALTER TABLE SETTLED_INVOICE_RECEIVED_VIA
    ADD FOREIGN KEY (SETTLED_INVOICE_JPA_DTO_ADD_INDEX) REFERENCES SETTLED_INVOICES (ADD_INDEX);

-- noinspection SqlWithoutWhere
DELETE FROM SETTLED_INVOICES;
